const hardQuestions = [
  /* =======================
        rank1（上級の入り口）
       ======================= */
  { level: "hard", rank: "1", kanji: "希薄", reading: "きはく" },
  { level: "hard", rank: "1", kanji: "抵抗", reading: "ていこう" },
  { level: "hard", rank: "1", kanji: "最適化", reading: "さいてきか" },
  { level: "hard", rank: "1", kanji: "精密", reading: "せいみつ" },
  { level: "hard", rank: "1", kanji: "抽出", reading: "ちゅうしゅつ" },
  { level: "hard", rank: "1", kanji: "均衡", reading: "きんこう" },
  { level: "hard", rank: "1", kanji: "錯覚", reading: "さっかく" },
  { level: "hard", rank: "1", kanji: "把握", reading: "はあく" },
  { level: "hard", rank: "1", kanji: "概算", reading: "がいさん" },
  { level: "hard", rank: "1", kanji: "堅固", reading: "けんご" },

  { level: "hard", rank: "1", kanji: "促進", reading: "そくしん" },
  { level: "hard", rank: "1", kanji: "潜在", reading: "せんざい" },
  { level: "hard", rank: "1", kanji: "緩和", reading: "かんわ" },
  { level: "hard", rank: "1", kanji: "均質", reading: "きんしつ" },
  { level: "hard", rank: "1", kanji: "継承", reading: "けいしょう" },
  { level: "hard", rank: "1", kanji: "抑制", reading: "よくせい" },
  { level: "hard", rank: "1", kanji: "排除", reading: "はいじょ" },
  { level: "hard", rank: "1", kanji: "抽選", reading: "ちゅうせん" },
  { level: "hard", rank: "1", kanji: "再編", reading: "さいへん" },
  { level: "hard", rank: "1", kanji: "照合", reading: "しょうごう" },

  { level: "hard", rank: "1", kanji: "弁証", reading: "べんしょう" },
  { level: "hard", rank: "1", kanji: "高揚", reading: "こうよう" },
  { level: "hard", rank: "1", kanji: "精査", reading: "せいさ" },
  { level: "hard", rank: "1", kanji: "滞納", reading: "たいのう" },
  { level: "hard", rank: "1", kanji: "介在", reading: "かいざい" },
  { level: "hard", rank: "1", kanji: "抽入", reading: "ちゅうにゅう" },
  { level: "hard", rank: "1", kanji: "堆積", reading: "たいせき" },
  { level: "hard", rank: "1", kanji: "動揺", reading: "どうよう" },
  { level: "hard", rank: "1", kanji: "錯乱", reading: "さくらん" },
  { level: "hard", rank: "1", kanji: "追憶", reading: "ついおく" },

  { level: "hard", rank: "1", kanji: "精妙", reading: "せいみょう" },
  { level: "hard", rank: "1", kanji: "懸架", reading: "けんか" },
  { level: "hard", rank: "1", kanji: "遡及", reading: "そきゅう" },
  { level: "hard", rank: "1", kanji: "干渉", reading: "かんしょう" },
  { level: "hard", rank: "1", kanji: "圧巻", reading: "あっかん" },
  { level: "hard", rank: "1", kanji: "緻密", reading: "ちみつ" },
  { level: "hard", rank: "1", kanji: "拘束", reading: "こうそく" },
  { level: "hard", rank: "1", kanji: "堅持", reading: "けんじ" },
  { level: "hard", rank: "1", kanji: "追随", reading: "ついずい" },
  { level: "hard", rank: "1", kanji: "逸話", reading: "いつわ" },

  { level: "hard", rank: "1", kanji: "均衡感覚", reading: "きんこうかんかく" },
  { level: "hard", rank: "1", kanji: "臨界点", reading: "りんかいてん" },
  { level: "hard", rank: "1", kanji: "精鋭部隊", reading: "せいえいぶたい" },
  { level: "hard", rank: "1", kanji: "意図的操作", reading: "いとてきそうさ" },
  { level: "hard", rank: "1", kanji: "抑圧構造", reading: "よくあつこうぞう" },
  { level: "hard", rank: "1", kanji: "分岐点", reading: "ぶんきてん" },
  { level: "hard", rank: "1", kanji: "概念整理", reading: "がいねんせいり" },
  { level: "hard", rank: "1", kanji: "軌跡計算", reading: "きせきけいさん" },
  {
    level: "hard",
    rank: "1",
    kanji: "高密度領域",
    reading: "こうみつどりょういき",
  },
  {
    level: "hard",
    rank: "1",
    kanji: "抑止力強化",
    reading: "よくしりょくきょうか",
  },

  /* =======================
        rank2（上級：本格的に難しい）
       ======================= */
  { level: "hard", rank: "2", kanji: "煩瑣", reading: "はんさ" },
  { level: "hard", rank: "2", kanji: "僭越", reading: "せんえつ" },
  { level: "hard", rank: "2", kanji: "矛盾律", reading: "むじゅんりつ" },
  { level: "hard", rank: "2", kanji: "形骸化", reading: "けいがいか" },
  { level: "hard", rank: "2", kanji: "峻別", reading: "しゅんべつ" },
  { level: "hard", rank: "2", kanji: "毀損", reading: "きそん" },
  { level: "hard", rank: "2", kanji: "驕慢", reading: "きょうまん" },
  { level: "hard", rank: "2", kanji: "逼迫", reading: "ひっぱく" },
  { level: "hard", rank: "2", kanji: "穿鑿", reading: "せんさく" },
  { level: "hard", rank: "2", kanji: "網羅", reading: "もうら" },

  { level: "hard", rank: "2", kanji: "煽動", reading: "せんどう" },
  { level: "hard", rank: "2", kanji: "頓挫", reading: "とんざ" },
  { level: "hard", rank: "2", kanji: "宥和", reading: "ゆうわ" },
  {
    level: "hard",
    rank: "2",
    kanji: "逼迫状況",
    reading: "ひっぱくじょうきょう",
  },
  {
    level: "hard",
    rank: "2",
    kanji: "限定的介入",
    reading: "げんていてきかいにゅう",
  },
  { level: "hard", rank: "2", kanji: "意匠登録", reading: "いしょうとうろく" },
  {
    level: "hard",
    rank: "2",
    kanji: "縮小均衡",
    reading: "しゅくしょうきんこう",
  },
  {
    level: "hard",
    rank: "2",
    kanji: "強制執行",
    reading: "きょうせいしっこう",
  },
  { level: "hard", rank: "2", kanji: "詭弁", reading: "きべん" },
  { level: "hard", rank: "2", kanji: "懐疑主義", reading: "かいぎしゅぎ" },

  { level: "hard", rank: "2", kanji: "忖度", reading: "そんたく" },
  { level: "hard", rank: "2", kanji: "越権行為", reading: "えっけんこうい" },
  { level: "hard", rank: "2", kanji: "毀誉褒貶", reading: "きよほうへん" },
  { level: "hard", rank: "2", kanji: "徒労感", reading: "とろうかん" },
  { level: "hard", rank: "2", kanji: "顕著", reading: "けんちょ" },
  { level: "hard", rank: "2", kanji: "精緻化", reading: "せいちか" },
  { level: "hard", rank: "2", kanji: "不可逆", reading: "ふかぎゃく" },
  { level: "hard", rank: "2", kanji: "難航", reading: "なんこう" },
  { level: "hard", rank: "2", kanji: "緩衝地帯", reading: "かんしょうちたい" },
  {
    level: "hard",
    rank: "2",
    kanji: "懲戒処分",
    reading: "ちょうかいしょぶん",
  },

  { level: "hard", rank: "2", kanji: "既成事実化", reading: "きせいじじつか" },
  { level: "hard", rank: "2", kanji: "専制政治", reading: "せんせいせいじ" },
  {
    level: "hard",
    rank: "2",
    kanji: "代償行動",
    reading: "だいしょうこうどう",
  },
  { level: "hard", rank: "2", kanji: "冗長性", reading: "じょうちょうせい" },
  { level: "hard", rank: "2", kanji: "複雑系", reading: "ふくざつけい" },
  { level: "hard", rank: "2", kanji: "矛盾構造", reading: "むじゅんこうぞう" },
  { level: "hard", rank: "2", kanji: "延滞金", reading: "えんたいきん" },
  {
    level: "hard",
    rank: "2",
    kanji: "限定合理性",
    reading: "げんていごうりせい",
  },
  { level: "hard", rank: "2", kanji: "依存構造", reading: "いぞんこうぞう" },
  {
    level: "hard",
    rank: "2",
    kanji: "排他的統制",
    reading: "はいたてきとうせい",
  },

  { level: "hard", rank: "2", kanji: "理不尽", reading: "りふじん" },
  { level: "hard", rank: "2", kanji: "懐古主義", reading: "かいこしゅぎ" },
  {
    level: "hard",
    rank: "2",
    kanji: "恒常性維持",
    reading: "こうじょうせいいじ",
  },
  { level: "hard", rank: "2", kanji: "相互依存", reading: "そうごいぞん" },
  {
    level: "hard",
    rank: "2",
    kanji: "代償性能",
    reading: "だいしょうせいのう",
  },
  { level: "hard", rank: "2", kanji: "権益争奪", reading: "けんえきそうだつ" },
  {
    level: "hard",
    rank: "2",
    kanji: "観念的構造",
    reading: "かんねんてきこうぞう",
  },
  { level: "hard", rank: "2", kanji: "特異点", reading: "とくいてん" },
  {
    level: "hard",
    rank: "2",
    kanji: "系統的整理",
    reading: "けいとうてきせいり",
  },
  { level: "hard", rank: "2", kanji: "拡散過程", reading: "かくさんかてい" },

  /* =======================
        rank3（上級：超難読多め）
       ======================= */
  { level: "hard", rank: "3", kanji: "煩悶", reading: "はんもん" },
  { level: "hard", rank: "3", kanji: "頽廃", reading: "たいはい" },
  { level: "hard", rank: "3", kanji: "靄", reading: "もや" },
  { level: "hard", rank: "3", kanji: "齟齬", reading: "そご" },
  { level: "hard", rank: "3", kanji: "膾炙", reading: "かいしゃ" },
  { level: "hard", rank: "3", kanji: "瑕疵", reading: "かし" },
  { level: "hard", rank: "3", kanji: "晦渋", reading: "かいじゅう" },
  { level: "hard", rank: "3", kanji: "醍醐味", reading: "だいごみ" },
  { level: "hard", rank: "3", kanji: "諧謔", reading: "かいぎゃく" },
  { level: "hard", rank: "3", kanji: "怯懦", reading: "きょうだ" },

  { level: "hard", rank: "3", kanji: "謬見", reading: "びゅうけん" },
  { level: "hard", rank: "3", kanji: "瞠目", reading: "どうもく" },
  { level: "hard", rank: "3", kanji: "奸計", reading: "かんけい" },
  { level: "hard", rank: "3", kanji: "朦朧", reading: "もうろう" },
  { level: "hard", rank: "3", kanji: "贅沢三昧", reading: "ぜいたくざんまい" },
  { level: "hard", rank: "3", kanji: "懊悩", reading: "おうのう" },
  { level: "hard", rank: "3", kanji: "拮抗作用", reading: "きっこうさよう" },
  { level: "hard", rank: "3", kanji: "警句", reading: "けいく" },
  { level: "hard", rank: "3", kanji: "鬼気迫る", reading: "ききせまる" },
  { level: "hard", rank: "3", kanji: "朧月", reading: "おぼろづき" },

  { level: "hard", rank: "3", kanji: "錯綜", reading: "さくそう" },
  { level: "hard", rank: "3", kanji: "放埒", reading: "ほうらつ" },
  { level: "hard", rank: "3", kanji: "竜頭蛇尾", reading: "りゅうとうだび" },
  { level: "hard", rank: "3", kanji: "深謀遠慮", reading: "しんぼうえんりょ" },
  { level: "hard", rank: "3", kanji: "陰鬱", reading: "いんうつ" },
  { level: "hard", rank: "3", kanji: "悔悟", reading: "かいご" },
  { level: "hard", rank: "3", kanji: "瞭然", reading: "りょうぜん" },
  { level: "hard", rank: "3", kanji: "豪胆", reading: "ごうたん" },
  { level: "hard", rank: "3", kanji: "艱難辛苦", reading: "かんなんしんく" },
  { level: "hard", rank: "3", kanji: "深淵", reading: "しんえん" },

  { level: "hard", rank: "3", kanji: "曖昧模糊", reading: "あいまいもこ" },
  { level: "hard", rank: "3", kanji: "曲解", reading: "きょっかい" },
  {
    level: "hard",
    rank: "3",
    kanji: "錯乱状態",
    reading: "さくらんじょうたい",
  },
  { level: "hard", rank: "3", kanji: "孤高", reading: "ここう" },
  { level: "hard", rank: "3", kanji: "独壇場", reading: "どくたんじょう" },
  { level: "hard", rank: "3", kanji: "奇怪", reading: "きかい" },
  { level: "hard", rank: "3", kanji: "特異現象", reading: "とくいげんしょう" },
  { level: "hard", rank: "3", kanji: "瀰漫", reading: "びまん" },
  {
    level: "hard",
    rank: "3",
    kanji: "不可侵領域",
    reading: "ふかしんりょういき",
  },
  { level: "hard", rank: "3", kanji: "幽玄", reading: "ゆうげん" },

  { level: "hard", rank: "BOSS", kanji: "冥利", reading: "みょうり" },
  { level: "hard", rank: "BOSS", kanji: "諫止", reading: "かんし" },
  { level: "hard", rank: "BOSS", kanji: "頽勢", reading: "たいせい" },
  { level: "hard", rank: "BOSS", kanji: "辟易", reading: "へきえき" },
  { level: "hard", rank: "BOSS", kanji: "涵養", reading: "かんよう" },

  { level: "hard", rank: "BOSS", kanji: "矜持", reading: "きょうじ、きんじ" },
  { level: "hard", rank: "BOSS", kanji: "老獪", reading: "ろうかい" },
  { level: "hard", rank: "BOSS", kanji: "杞憂", reading: "きゆう" },
  { level: "hard", rank: "BOSS", kanji: "潤沢", reading: "じゅんたく" },
  { level: "hard", rank: "BOSS", kanji: "慇懃", reading: "いんぎん" },

  { level: "hard", rank: "BOSS", kanji: "罷免", reading: "ひめん" },
  { level: "hard", rank: "BOSS", kanji: "饒舌", reading: "じょうぜつ" },
  { level: "hard", rank: "BOSS", kanji: "誅罰", reading: "ちゅうばつ" },
  { level: "hard", rank: "BOSS", kanji: "醜悪", reading: "しゅうあく" },
  { level: "hard", rank: "BOSS", kanji: "懊恨", reading: "おうこん" },

  { level: "hard", rank: "BOSS", kanji: "傲岸", reading: "ごうがん" },
  { level: "hard", rank: "BOSS", kanji: "扼要", reading: "やくよう" },
  { level: "hard", rank: "BOSS", kanji: "咀嚼", reading: "そしゃく" },
  { level: "hard", rank: "BOSS", kanji: "多弁", reading: "たべん" },
  {
    level: "hard",
    rank: "BOSS",
    kanji: "欝金香",
    reading: "うこんこう（チューリップ）",
  },

  { level: "hard", rank: "BOSS", kanji: "窮地", reading: "きゅうち" },
  { level: "hard", rank: "BOSS", kanji: "荘厳", reading: "そうごん" },
  { level: "hard", rank: "BOSS", kanji: "毀壊", reading: "きかい" },
  { level: "hard", rank: "BOSS", kanji: "驟雨", reading: "しゅうう" },
  { level: "hard", rank: "BOSS", kanji: "累卵", reading: "るいらん" },

  {
    level: "hard",
    rank: "BOSS",
    kanji: "玉石混淆",
    reading: "ぎょくせきこんこう",
  },
  {
    level: "hard",
    rank: "BOSS",
    kanji: "深窓令嬢",
    reading: "しんそうれいじょう",
  },
  {
    level: "hard",
    rank: "BOSS",
    kanji: "恣意的解釈",
    reading: "しいてきかいしゃく",
  },
  {
    level: "hard",
    rank: "BOSS",
    kanji: "情状酌量",
    reading: "じょうじょうしゃくりょう",
  },
  { level: "hard", rank: "BOSS", kanji: "不撓不屈", reading: "ふとうふくつ" },

  { level: "hard", rank: "BOSS", kanji: "窮余の策", reading: "きゅうよのさく" },
  { level: "hard", rank: "BOSS", kanji: "勇猛果敢", reading: "ゆうもうかかん" },
  { level: "hard", rank: "BOSS", kanji: "無謬性", reading: "むびゅうせい" },
  {
    level: "hard",
    rank: "BOSS",
    kanji: "虚心坦懐",
    reading: "きょしんたんかい",
  },
  { level: "hard", rank: "BOSS", kanji: "強靭", reading: "きょうじん" },

  { level: "hard", rank: "BOSS", kanji: "欺瞞", reading: "ぎまん" },
  { level: "hard", rank: "BOSS", kanji: "辣腕", reading: "らつわん" },
  { level: "hard", rank: "BOSS", kanji: "曖昧", reading: "あいまい" },
  { level: "hard", rank: "BOSS", kanji: "偏執", reading: "へんしつ" },
  { level: "hard", rank: "BOSS", kanji: "戦慄", reading: "せんりつ" },

  { level: "hard", rank: "BOSS", kanji: "明察", reading: "めいさつ" },
  { level: "hard", rank: "BOSS", kanji: "冷厳", reading: "れいげん" },
  { level: "hard", rank: "BOSS", kanji: "驕奢", reading: "きょうしゃ" },
  { level: "hard", rank: "BOSS", kanji: "洞察力", reading: "どうさつりょく" },
  { level: "hard", rank: "BOSS", kanji: "虚無感", reading: "きょむかん" },

  {
    level: "hard",
    rank: "BOSS",
    kanji: "不可逆変化",
    reading: "ふかぎゃくへんか",
  },
  { level: "hard", rank: "BOSS", kanji: "神秘主義", reading: "しんぴしゅぎ" },
  {
    level: "hard",
    rank: "BOSS",
    kanji: "破邪顕正",
    reading: "はじゃけんしょう",
  },
  { level: "hard", rank: "BOSS", kanji: "非業の死", reading: "ひごうのし" },
  {
    level: "hard",
    rank: "BOSS",
    kanji: "形骸的手続",
    reading: "けいがいてきてつづき",
  },
];

export default hardQuestions;
